# Generated by Django 2.1.2 on 2018-11-12 21:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adoptador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('ap_paterno', models.CharField(max_length=200)),
                ('ap_materno', models.CharField(max_length=200)),
                ('rut', models.CharField(max_length=12)),
                ('direccion', models.TextField()),
                ('telefono', models.IntegerField()),
                ('email', models.CharField(max_length=200)),
                ('genero', models.CharField(max_length=1)),
                ('fecha_nacimiento', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Perro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('raza', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=20)),
                ('fecha_encontrado', models.DateTimeField(default=django.utils.timezone.now)),
                ('edad_estimada', models.IntegerField()),
                ('sitio_encontrado', models.CharField(max_length=200)),
                ('fecha_publicacion', models.DateTimeField(blank=True, null=True)),
                ('adoptador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='perrisapp.Adoptador')),
            ],
        ),
    ]
