# Generated by Django 2.1.2 on 2018-11-13 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perrisapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adoptador',
            old_name='nombre',
            new_name='nombre_completo',
        ),
        migrations.AddField(
            model_name='adoptador',
            name='comentario',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='adoptador',
            name='direccion',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='adoptador',
            name='fecha_nacimiento',
            field=models.DateField(),
        ),
    ]
